name: "Dc Dev Actions"
description: "A collection the DC Dev actions"

inputs:
  message:
    description: "Message to display"
    required: false
    default: "from Dc Dev Actions"

runs:
  using: "composite"

  steps:
    - name: "Hello World"
      id: "Hola"
      uses: "actions/hello-world-javascript-action@v1"
      with:
        who-to-greet: "${{ inputs.message }}"
    - name: "Print greeting"
      shell: bash
      run: |
        echo "Greeting: ${{ steps.Hola.outputs.greeting }}"
        echo "Hola Mundo desde Dc Dev Actions"
