name: List File Actions
description: "List all files in the repository"

runs:
  using: "composite"

  steps:
    - name: List all files
      shell: bash
      run: |
        echo "Listing all files in the repository:"
        ls -la
        echo "Current directory:"
        pwd
        echo "Files in the current directory:"
        ls -la .
        echo "Files in the parent directory:"
        ls -la ..

# Example usage:
#  - name: List all files
#    uses: ./.github/actions/list_file_actions
