name: Workflow Studied
on: [push]
jobs:
  saludo:
    name: Saludo Job
    runs-on: ubuntu-latest

    env:
      NAME_DEV: Dc Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Saludo
        uses: ./.github/actions/dc_dev_actions
        with:
          message: Hola Mundo desde $NAME_DEV Actions
      - name: bash test
        shell: bash
        run: |
          echo "Hola Mundo desde Dc Dev Actions"
          echo "Hola Mundo desde $NAME_DEV Actions"
