name: Workflow Studied
on: [push]
jobs:
  saludo:
    name: Saludo job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7
      - name: Saludo
        uses: ./.github/actions/dc_dev_actions
        with:
          message: "Hola Mundo desde ${{ secrets.NAME_DEV }} Actions"
      - name: bash test
        shell: bash
        env:
          ENV_NAME_DEV: "Dc Dev"
          NAME_DEV: ${{ vars.DEV_NAME }}
          REPO_NAME: ${{ github.repository }}
          SECRET_DEV_NAME: ${{ secrets.NAME_DEV }}
        run: |
          echo "Hola Mundo desde $ENV_NAME_DEV"
          echo "Hola Mundo desde $NAME_DEV"
          echo "Hola Mundo desde $SECRET_DEV_NAME (secreto)"
          echo "Repository: $REPO_NAME"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
