name: Workflow Studied -> CI/CD with Slack Notifications
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: npm test

      - name: Test Success Notification
        if: success()
        uses: ./.github/actions/slack_webhooks
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOKS }}
          title: "Tests Passed ✅"
          message: "All tests are passing on branch ${{ github.ref_name }}"
          status: "success"

      - name: Test Failure Notification
        if: failure()
        uses: ./.github/actions/slack_webhooks
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOKS }}
          title: "Tests Failed ❌"
          message: "Tests are failing on branch ${{ github.ref_name }}. Please check the logs."
          status: "failure"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Application
        run: echo "Deploying..."

      - name: Deploy Success Notification
        if: success()
        uses: ./.github/actions/slack_webhooks
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOKS }}
          title: "🚀 Production Deploy Successful"
          message: |
            Production deployment completed!

            **Commit:** ${{ github.event.head_commit.message }}
            **Author:** ${{ github.event.head_commit.author.name }}
          status: "success"
          channel: "#deployments"

      - name: Deploy Failure Notification
        if: failure()
        uses: ./.github/actions/slack_webhooks
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOKS }}
          title: "🚨 Production Deploy Failed"
          message: "Production deployment failed! Immediate attention required."
          status: "failure"
          channel: "#critical-alerts"
